## Perform

Unified long-table evaluation. Final outputs are **mean-based summaries** (not totals).

In [18]:
import pandas as pd
from inventory_performance_eval import OUTPUT_COLUMNS, collect_base_vs_ir_results

LEAD_TIME = 1
prefix = ''

# Basic Performance

In [4]:
all_results_long = collect_base_vs_ir_results(
    lead_time=LEAD_TIME,
    filename_prefix=prefix,
)
all_results_long = all_results_long[OUTPUT_COLUMNS]
all_results_long

,Levels,Forecast_Methods,Target_Service_Level,Senario,Achieved_Service_Level,Holding_Costs,Backlogging_Costs,Fill_Rate
0,10,LGBM,90%,BASE,0.312725,1.097069,82.888175,0.777973
1,10,LGBM,95%,BASE,0.382409,1.550911,151.289022,0.804119
2,10,LGBM,99%,BASE,0.512522,2.729227,589.049170,0.850145
3,11,LGBM,90%,BASE,0.532583,1.243050,24.460532,0.755767
4,11,LGBM,95%,BASE,0.600900,1.673165,42.846375,0.794490
...,...,...,...,...,...,...,...,...
247,11,ETS_MinT,95%,WLS_VAR_OR,0.612839,1.779242,39.553146,0.802874
248,11,ETS_MinT,99%,WLS_VAR_OR,0.728065,2.889353,137.900960,0.863337
249,12,ETS_MinT,90%,WLS_VAR_OR,0.596638,0.709573,9.102195,0.614523
250,12,ETS_MinT,95%,WLS_VAR_OR,0.637237,0.872007,16.835690,0.654604
251,12,ETS_MinT,99%,WLS_VAR_OR,0.705339,1.216140,68.356813,0.720563

In [13]:
a = all_results_long[all_results_long['Forecast_Methods'].str.contains('ETS')]

In [14]:
a.to_csv('ETS_perform.csv', index = False)

In [15]:
b = all_results_long[all_results_long['Forecast_Methods'].str.contains('LGBM')]
b.to_csv('LGBM_perform.csv', index = False)

In [16]:
a = b
a[a['Senario'] == 'BASE']

,Levels,Forecast_Methods,Target_Service_Level,Senario,Achieved_Service_Level,Holding_Costs,Backlogging_Costs,Fill_Rate
0,10,LGBM,90%,BASE,0.312725,1.097069,82.888175,0.777973
1,10,LGBM,95%,BASE,0.382409,1.550911,151.289022,0.804119
2,10,LGBM,99%,BASE,0.512522,2.729227,589.049170,0.850145
3,11,LGBM,90%,BASE,0.532583,1.243050,24.460532,0.755767
4,11,LGBM,95%,BASE,0.600900,1.673165,42.846375,0.794490
5,11,LGBM,99%,BASE,0.710893,2.659701,155.104693,0.854343
6,12,LGBM,90%,BASE,0.701848,1.129360,6.955398,0.722660
7,12,LGBM,95%,BASE,0.753359,1.432735,11.891484,0.771343
8,12,LGBM,99%,BASE,0.828752,2.072183,41.636629,0.840733
9,10,LGBM_BU,90%,BASE,0.358748,1.309554,82.787969,0.808710
10,10,LGBM_BU,95%,BASE,0.424179,1.796228,151.154657,0.832377
11,10,LGBM_BU,99%,BASE,0.546186,3.030790,588.574768,0.872816
12,11,LGBM_BU,90%,BASE,0.547732,1.300622,24.531483,0.773251
13,11,LGBM_BU,95%,BASE,0.613374,1.731901,43.016424,0.809689
14,11,LGBM_BU,99%,BASE,0.720002,2.718342,155.963146,0.865578
15,12,LGBM_BU,90%,BASE,0.701848,1.129360,6.955398,0.722660
16,12,LGBM_BU,95%,BASE,0.753359,1.432735,11.891484,0.771343
17,12,LGBM_BU,99%,BASE,0.828752,2.072183,41.636629,0.840733
18,10,LGBM_TD,90%,BASE,0.312725,1.097069,82.888175,0.777973
19,10,LGBM_TD,95%,BASE,0.382409,1.550911,151.289022,0.804119
20,10,LGBM_TD,99%,BASE,0.512522,2.729227,589.049170,0.850145
21,11,LGBM_TD,90%,BASE,0.530514,1.237663,24.257588,0.751353
22,11,LGBM_TD,95%,BASE,0.599471,1.668738,42.436177,0.790842
23,11,LGBM_TD,99%,BASE,0.710092,2.658193,153.256320,0.851837
24,12,LGBM_TD,90%,BASE,0.694242,1.106826,6.870350,0.706797
25,12,LGBM_TD,95%,BASE,0.747123,1.410679,11.721008,0.758144
26,12,LGBM_TD,99%,BASE,0.825098,2.051603,40.894456,0.831778
27,10,LGBM_MinT,90%,BASE,0.307126,1.102334,82.573612,0.779557
28,10,LGBM_MinT,95%,BASE,0.373483,1.542977,151.300235,0.804769
29,10,LGBM_MinT,99%,BASE,0.502472,2.680610,594.131741,0.849541
30,11,LGBM_MinT,90%,BASE,0.525543,1.227089,24.292399,0.750052
31,11,LGBM_MinT,95%,BASE,0.593469,1.645812,42.721671,0.788900
32,11,LGBM_MinT,99%,BASE,0.702943,2.602708,155.886583,0.849269
33,12,LGBM_MinT,90%,BASE,0.692820,1.109209,6.889944,0.705712
34,12,LGBM_MinT,95%,BASE,0.745009,1.407605,11.813582,0.756007
35,12,LGBM_MinT,99%,BASE,0.821819,2.035844,41.634746,0.828741

In [17]:
a[a['Senario'] == 'BU_OR']

,Levels,Forecast_Methods,Target_Service_Level,Senario,Achieved_Service_Level,Holding_Costs,Backlogging_Costs,Fill_Rate
72,10,LGBM,90%,BU_OR,0.774774,7.188980,31.588636,0.941992
73,10,LGBM,95%,BU_OR,0.854214,10.546357,44.914617,0.962584
74,10,LGBM,99%,BU_OR,0.929181,17.749414,110.835017,0.981291
75,11,LGBM,90%,BU_OR,0.735756,2.821518,14.438737,0.873529
76,11,LGBM,95%,BU_OR,0.806447,3.885295,22.172641,0.908636
77,11,LGBM,99%,BU_OR,0.891569,6.178744,63.817143,0.948604
78,12,LGBM,90%,BU_OR,0.701848,1.129360,6.955398,0.722660
79,12,LGBM,95%,BU_OR,0.753359,1.432735,11.891484,0.771343
80,12,LGBM,99%,BU_OR,0.828752,2.072183,41.636629,0.840733
81,10,LGBM_BU,90%,BU_OR,0.766996,7.192810,32.646894,0.942501
82,10,LGBM_BU,95%,BU_OR,0.846636,10.497565,46.148885,0.962742
83,10,LGBM_BU,99%,BU_OR,0.926217,17.650126,112.267083,0.981845
84,11,LGBM_BU,90%,BU_OR,0.735241,2.834975,14.818639,0.878195
85,11,LGBM_BU,95%,BU_OR,0.804542,3.888018,22.770723,0.911736
86,11,LGBM_BU,99%,BU_OR,0.890085,6.166299,65.431850,0.950386
87,12,LGBM_BU,90%,BU_OR,0.701848,1.129360,6.955398,0.722660
88,12,LGBM_BU,95%,BU_OR,0.753359,1.432735,11.891484,0.771343
89,12,LGBM_BU,99%,BU_OR,0.828752,2.072183,41.636629,0.840733
90,10,LGBM_TD,90%,BU_OR,0.761257,6.899956,31.188745,0.936236
91,10,LGBM_TD,95%,BU_OR,0.844902,10.226984,43.493756,0.959201
92,10,LGBM_TD,99%,BU_OR,0.926463,17.421310,102.567251,0.980208
93,11,LGBM_TD,90%,BU_OR,0.726819,2.744837,14.399913,0.865536
94,11,LGBM_TD,95%,BU_OR,0.800083,3.802907,21.982245,0.902923
95,11,LGBM_TD,99%,BU_OR,0.888168,6.091795,62.373501,0.945726
96,12,LGBM_TD,90%,BU_OR,0.694242,1.106826,6.870350,0.706797
97,12,LGBM_TD,95%,BU_OR,0.747123,1.410679,11.721008,0.758144
98,12,LGBM_TD,99%,BU_OR,0.825098,2.051603,40.894456,0.831778
99,10,LGBM_MinT,90%,BU_OR,0.758797,6.939920,31.529924,0.937441
100,10,LGBM_MinT,95%,BU_OR,0.842384,10.206216,44.608930,0.959559
101,10,LGBM_MinT,99%,BU_OR,0.924366,17.254265,109.034482,0.980085
102,11,LGBM_MinT,90%,BU_OR,0.725331,2.755660,14.491156,0.866809
103,11,LGBM_MinT,95%,BU_OR,0.797385,3.793670,22.310010,0.903206
104,11,LGBM_MinT,99%,BU_OR,0.885771,6.035489,64.467453,0.945289
105,12,LGBM_MinT,90%,BU_OR,0.692820,1.109209,6.889944,0.705712
106,12,LGBM_MinT,95%,BU_OR,0.745009,1.407605,11.813582,0.756007
107,12,LGBM_MinT,99%,BU_OR,0.821819,2.035844,41.634746,0.828741

In [9]:
a[a['Senario'] == 'TDFP_OR']

,Levels,Forecast_Methods,Target_Service_Level,Senario,Achieved_Service_Level,Holding_Costs,Backlogging_Costs,Fill_Rate
180,10,ETS,90%,TDFP_OR,0.323701,1.269728,77.731422,0.779663
181,10,ETS,95%,TDFP_OR,0.397601,1.816297,139.204508,0.805777
182,10,ETS,99%,TDFP_OR,0.532692,3.235012,520.952246,0.852120
183,11,ETS,90%,TDFP_OR,0.415027,0.789588,29.871387,0.683793
184,11,ETS,95%,TDFP_OR,0.466109,1.014376,55.572804,0.712420
185,11,ETS,99%,TDFP_OR,0.559504,1.533456,226.009400,0.762889
186,12,ETS,90%,TDFP_OR,0.524159,0.487991,11.408127,0.526325
187,12,ETS,95%,TDFP_OR,0.548413,0.571628,22.144923,0.552084
188,12,ETS,99%,TDFP_OR,0.594004,0.746884,98.254201,0.599082
189,10,ETS_BU,90%,TDFP_OR,0.320866,1.242647,78.050917,0.784407
190,10,ETS_BU,95%,TDFP_OR,0.394509,1.797889,139.636143,0.810158
191,10,ETS_BU,99%,TDFP_OR,0.532399,3.236704,521.206926,0.855628
192,11,ETS_BU,90%,TDFP_OR,0.415031,0.776361,29.276283,0.688534
193,11,ETS_BU,95%,TDFP_OR,0.467382,1.007414,54.299617,0.717283
194,11,ETS_BU,99%,TDFP_OR,0.562148,1.541045,219.487853,0.767737
195,12,ETS_BU,90%,TDFP_OR,0.527178,0.480663,11.012672,0.529632
196,12,ETS_BU,95%,TDFP_OR,0.552379,0.566920,21.319112,0.555938
197,12,ETS_BU,99%,TDFP_OR,0.598827,0.748068,94.136027,0.603772
198,10,ETS_TD,90%,TDFP_OR,0.323701,1.269728,77.731422,0.779663
199,10,ETS_TD,95%,TDFP_OR,0.397601,1.816297,139.204508,0.805777
200,10,ETS_TD,99%,TDFP_OR,0.532692,3.235012,520.952246,0.852120
201,11,ETS_TD,90%,TDFP_OR,0.417213,0.792897,29.237367,0.684481
202,11,ETS_TD,95%,TDFP_OR,0.468573,1.020942,54.296195,0.713271
203,11,ETS_TD,99%,TDFP_OR,0.561706,1.546895,220.038013,0.763994
204,12,ETS_TD,90%,TDFP_OR,0.527247,0.490081,11.041120,0.527981
205,12,ETS_TD,95%,TDFP_OR,0.551504,0.575167,21.397656,0.553946
206,12,ETS_TD,99%,TDFP_OR,0.597738,0.753587,94.673711,0.601211
207,10,ETS_MinT,90%,TDFP_OR,0.284250,1.035870,84.851344,0.776467
208,10,ETS_MinT,95%,TDFP_OR,0.351099,1.438282,155.139548,0.799667
209,10,ETS_MinT,99%,TDFP_OR,0.478049,2.500871,604.333390,0.842464
210,11,ETS_MinT,90%,TDFP_OR,0.389624,0.683502,31.327687,0.677990
211,11,ETS_MinT,95%,TDFP_OR,0.437622,0.866290,59.063568,0.704385
212,11,ETS_MinT,99%,TDFP_OR,0.524227,1.287892,246.417067,0.751499
213,12,ETS_MinT,90%,TDFP_OR,0.509609,0.450219,11.604818,0.521376
214,12,ETS_MinT,95%,TDFP_OR,0.533060,0.522241,22.703791,0.545001
215,12,ETS_MinT,99%,TDFP_OR,0.576127,0.672741,102.276036,0.588437

In [12]:
# Optional save
# all_results_long.to_pickle(f"all_inventory_results_long_L{LEAD_TIME}.pkl")
# all_results_long.to_csv(f"all_inventory_results_long_L{LEAD_TIME}.csv", index=False)

# Mean table by scenario / level / target service level
all_results_long.sort_values(['Senario', 'Forecast_Methods', 'Levels', 'Target_Service_Level']).reset_index(drop=True)

# BWE

In [ ]:
collect_base_vs_ir_results

all_results_long = collect_base_vs_ir_results(
    lead_time=LEAD_TIME,
    filename_prefix=prefix,
)