## Perform

Unified long-table evaluation. Final outputs are **mean-based summaries** (not totals).

In [1]:
import pandas as pd
from inventory_performance_eval import OUTPUT_COLUMNS, collect_base_vs_ir_results

LEAD_TIME = 1
prefix = ''

# Basic Performance

In [2]:
all_results_long = collect_base_vs_ir_results(
    lead_time=LEAD_TIME,
    filename_prefix=prefix,
)
all_results_long = all_results_long[OUTPUT_COLUMNS]
all_results_long

,Levels,Forecast_Methods,Target_Service_Level,Senario,Achieved_Service_Level,Holding_Costs,Backlogging_Costs,Fill_Rate
0,10,LGBM,90%,BASE,0.857143,6.340248,4.448255,0.949918
1,10,LGBM,95%,BASE,0.897566,7.888741,6.491999,0.964040
2,10,LGBM,99%,BASE,0.942792,10.928069,18.820656,0.979051
3,11,LGBM,90%,BASE,0.869782,3.454602,2.512626,0.914778
4,11,LGBM,95%,BASE,0.905082,4.268535,3.804559,0.936449
...,...,...,...,...,...,...,...,...
283,11,ETS_MinT,95%,WLS_VAR_OR,0.908932,4.489914,3.507346,0.935949
284,11,ETS_MinT,99%,WLS_VAR_OR,0.947008,6.211284,10.504985,0.961092
285,12,ETS_MinT,90%,WLS_VAR_OR,0.816311,1.308883,2.099568,0.742274
286,12,ETS_MinT,95%,WLS_VAR_OR,0.844990,1.556003,3.663692,0.780554
287,12,ETS_MinT,99%,WLS_VAR_OR,0.885965,2.041593,13.719626,0.836553

In [3]:
a = all_results_long[all_results_long['Forecast_Methods'].str.contains('ETS')]

In [4]:
a.to_csv('ETS_perform.csv', index = False)

In [5]:
b = all_results_long[all_results_long['Forecast_Methods'].str.contains('LGBM')]
b.to_csv('LGBM_perform.csv', index = False)

In [6]:
a = b
a[a['Senario'] == 'BASE']

,Levels,Forecast_Methods,Target_Service_Level,Senario,Achieved_Service_Level,Holding_Costs,Backlogging_Costs,Fill_Rate
0,10,LGBM,90%,BASE,0.857143,6.340248,4.448255,0.949918
1,10,LGBM,95%,BASE,0.897566,7.888741,6.491999,0.964040
2,10,LGBM,99%,BASE,0.942792,10.928069,18.820656,0.979051
3,11,LGBM,90%,BASE,0.869782,3.454602,2.512626,0.914778
4,11,LGBM,95%,BASE,0.905082,4.268535,3.804559,0.936449
5,11,LGBM,99%,BASE,0.944061,5.861147,11.677805,0.960784
6,12,LGBM,90%,BASE,0.887333,1.900468,1.341056,0.849247
7,12,LGBM,95%,BASE,0.915142,2.313842,2.129578,0.884496
8,12,LGBM,99%,BASE,0.947320,3.117103,6.991053,0.925800
9,10,LGBM_BU,90%,BASE,0.879246,6.562988,4.383359,0.963589
10,10,LGBM_BU,95%,BASE,0.913520,8.140750,6.364509,0.973956
11,10,LGBM_BU,99%,BASE,0.951670,11.236296,18.379317,0.984802
12,11,LGBM_BU,90%,BASE,0.878457,3.505221,2.488138,0.926105
13,11,LGBM_BU,95%,BASE,0.911318,4.319773,3.762645,0.945194
14,11,LGBM_BU,99%,BASE,0.948051,5.913321,11.533889,0.966285
15,12,LGBM_BU,90%,BASE,0.887333,1.900468,1.341056,0.849247
16,12,LGBM_BU,95%,BASE,0.915142,2.313842,2.129578,0.884496
17,12,LGBM_BU,99%,BASE,0.947320,3.117103,6.991053,0.925800
18,10,LGBM_TD,90%,BASE,0.857143,6.340248,4.448255,0.949918
19,10,LGBM_TD,95%,BASE,0.897566,7.888741,6.491999,0.964040
20,10,LGBM_TD,99%,BASE,0.942792,10.928069,18.820656,0.979051
21,11,LGBM_TD,90%,BASE,0.868700,3.469852,2.485227,0.911974
22,11,LGBM_TD,95%,BASE,0.904289,4.284895,3.767851,0.934428
23,11,LGBM_TD,99%,BASE,0.943561,5.878409,11.575970,0.959584
24,12,LGBM_TD,90%,BASE,0.882464,1.886047,1.338858,0.833577
25,12,LGBM_TD,95%,BASE,0.911159,2.299542,2.127327,0.872296
26,12,LGBM_TD,99%,BASE,0.945139,3.102924,6.991255,0.918494
27,10,LGBM_MinT,90%,BASE,0.855175,6.380189,4.350926,0.949393
28,10,LGBM_MinT,95%,BASE,0.895012,7.887473,6.429660,0.963267
29,10,LGBM_MinT,99%,BASE,0.940753,10.840321,18.985982,0.978444
30,11,LGBM_MinT,90%,BASE,0.866334,3.457069,2.468672,0.909923
31,11,LGBM_MinT,95%,BASE,0.901888,4.250714,3.772924,0.932521
32,11,LGBM_MinT,99%,BASE,0.941495,5.801454,11.733631,0.958153
33,12,LGBM_MinT,90%,BASE,0.881476,1.886980,1.337328,0.831392
34,12,LGBM_MinT,95%,BASE,0.909667,2.292978,2.136557,0.869457
35,12,LGBM_MinT,99%,BASE,0.943356,3.081461,7.078187,0.915573

In [7]:
a[a['Senario'] == 'BU_OR']

,Levels,Forecast_Methods,Target_Service_Level,Senario,Achieved_Service_Level,Holding_Costs,Backlogging_Costs,Fill_Rate
72,10,LGBM,90%,BU_OR,0.978143,17.722331,0.845639,0.991418
73,10,LGBM,95%,BU_OR,0.981668,22.208045,1.457319,0.992453
74,10,LGBM,99%,BU_OR,0.983379,30.646880,6.758251,0.993004
75,11,LGBM,90%,BU_OR,0.951311,5.980364,1.020626,0.966535
76,11,LGBM,95%,BU_OR,0.966257,7.446482,1.492067,0.975746
77,11,LGBM,99%,BU_OR,0.978521,10.234863,5.064315,0.983331
78,12,LGBM,90%,BU_OR,0.887333,1.900468,1.341056,0.849247
79,12,LGBM,95%,BU_OR,0.915142,2.313842,2.129578,0.884496
80,12,LGBM,99%,BU_OR,0.947320,3.117103,6.991053,0.925800
81,10,LGBM_BU,90%,BU_OR,0.978377,17.611909,0.875629,0.992709
82,10,LGBM_BU,95%,BU_OR,0.982160,22.096920,1.507261,0.993656
83,10,LGBM_BU,99%,BU_OR,0.983835,30.535550,6.998181,0.994154
84,11,LGBM_BU,90%,BU_OR,0.951838,5.954320,1.045027,0.969569
85,11,LGBM_BU,95%,BU_OR,0.966804,7.419303,1.522015,0.977998
86,11,LGBM_BU,99%,BU_OR,0.978849,10.206935,5.146149,0.984894
87,12,LGBM_BU,90%,BU_OR,0.887333,1.900468,1.341056,0.849247
88,12,LGBM_BU,95%,BU_OR,0.915142,2.313842,2.129578,0.884496
89,12,LGBM_BU,99%,BU_OR,0.947320,3.117103,6.991053,0.925800
90,10,LGBM_TD,90%,BU_OR,0.977522,17.464218,0.822311,0.991129
91,10,LGBM_TD,95%,BU_OR,0.981469,21.951366,1.436310,0.992377
92,10,LGBM_TD,99%,BU_OR,0.983332,30.391235,6.750355,0.992989
93,11,LGBM_TD,90%,BU_OR,0.948777,5.904540,1.022309,0.963798
94,11,LGBM_TD,95%,BU_OR,0.965000,7.370323,1.489585,0.974185
95,11,LGBM_TD,99%,BU_OR,0.978049,10.158844,5.064926,0.982687
96,12,LGBM_TD,90%,BU_OR,0.882464,1.886047,1.338858,0.833577
97,12,LGBM_TD,95%,BU_OR,0.911159,2.299542,2.127327,0.872296
98,12,LGBM_TD,99%,BU_OR,0.945139,3.102924,6.991255,0.918494
99,10,LGBM_MinT,90%,BU_OR,0.977358,17.474496,0.815576,0.991287
100,10,LGBM_MinT,95%,BU_OR,0.981364,21.880300,1.425450,0.992489
101,10,LGBM_MinT,99%,BU_OR,0.983191,30.166835,6.651998,0.993109
102,11,LGBM_MinT,90%,BU_OR,0.948371,5.907376,1.014760,0.963959
103,11,LGBM_MinT,95%,BU_OR,0.964383,7.346835,1.489773,0.974138
104,11,LGBM_MinT,99%,BU_OR,0.977557,10.084474,5.074701,0.982667
105,12,LGBM_MinT,90%,BU_OR,0.881476,1.886980,1.337328,0.831392
106,12,LGBM_MinT,95%,BU_OR,0.909667,2.292978,2.136557,0.869457
107,12,LGBM_MinT,99%,BU_OR,0.943356,3.081461,7.078187,0.915573

In [8]:
a[a['Senario'] == 'TDFP_OR']

,Levels,Forecast_Methods,Target_Service_Level,Senario,Achieved_Service_Level,Holding_Costs,Backlogging_Costs,Fill_Rate
144,10,LGBM,90%,TDFP_OR,0.857143,6.340248,4.448255,0.949918
145,10,LGBM,95%,TDFP_OR,0.897566,7.888741,6.491999,0.964040
146,10,LGBM,99%,TDFP_OR,0.942792,10.928069,18.820656,0.979051
147,11,LGBM,90%,TDFP_OR,0.763424,2.456867,4.656271,0.846575
148,11,LGBM,95%,TDFP_OR,0.804077,2.921795,7.890174,0.871499
149,11,LGBM,99%,TDFP_OR,0.862187,3.850501,27.754021,0.907390
150,12,LGBM,90%,TDFP_OR,0.700177,1.019925,4.020305,0.653378
151,12,LGBM,95%,TDFP_OR,0.724100,1.147079,7.671227,0.679137
152,12,LGBM,99%,TDFP_OR,0.764027,1.397267,33.149790,0.722765
153,10,LGBM_BU,90%,TDFP_OR,0.879246,6.562988,4.383359,0.963589
154,10,LGBM_BU,95%,TDFP_OR,0.913520,8.140750,6.364509,0.973956
155,10,LGBM_BU,99%,TDFP_OR,0.951670,11.236296,18.379317,0.984802
156,11,LGBM_BU,90%,TDFP_OR,0.791438,2.505644,4.322953,0.872309
157,11,LGBM_BU,95%,TDFP_OR,0.829195,2.985060,7.279554,0.894492
158,11,LGBM_BU,99%,TDFP_OR,0.881390,3.939631,25.352166,0.925760
159,12,LGBM_BU,90%,TDFP_OR,0.713325,1.020594,3.716991,0.666443
160,12,LGBM_BU,95%,TDFP_OR,0.736997,1.152470,7.065961,0.692537
161,12,LGBM_BU,99%,TDFP_OR,0.776718,1.411482,30.335354,0.736479
162,10,LGBM_TD,90%,TDFP_OR,0.857143,6.340248,4.448255,0.949918
163,10,LGBM_TD,95%,TDFP_OR,0.897566,7.888741,6.491999,0.964040
164,10,LGBM_TD,99%,TDFP_OR,0.942792,10.928069,18.820656,0.979051
165,11,LGBM_TD,90%,TDFP_OR,0.769706,2.443660,4.454951,0.846651
166,11,LGBM_TD,95%,TDFP_OR,0.809352,2.912405,7.537658,0.871799
167,11,LGBM_TD,99%,TDFP_OR,0.866229,3.847136,26.513724,0.907827
168,12,LGBM_TD,90%,TDFP_OR,0.704523,1.004957,3.783219,0.644998
169,12,LGBM_TD,95%,TDFP_OR,0.728297,1.134220,7.210767,0.671184
170,12,LGBM_TD,99%,TDFP_OR,0.768186,1.388006,31.106771,0.715596
171,10,LGBM_MinT,90%,TDFP_OR,0.855175,6.380189,4.350926,0.949393
172,10,LGBM_MinT,95%,TDFP_OR,0.895012,7.887473,6.429660,0.963267
173,10,LGBM_MinT,99%,TDFP_OR,0.940753,10.840321,18.985982,0.978444
174,11,LGBM_MinT,90%,TDFP_OR,0.768710,2.450277,4.362238,0.845642
175,11,LGBM_MinT,95%,TDFP_OR,0.808169,2.906999,7.422209,0.870487
176,11,LGBM_MinT,99%,TDFP_OR,0.864206,3.815420,26.324593,0.906350
177,12,LGBM_MinT,90%,TDFP_OR,0.705196,1.003566,3.725014,0.642128
178,12,LGBM_MinT,95%,TDFP_OR,0.728650,1.129819,7.123321,0.667648
179,12,LGBM_MinT,99%,TDFP_OR,0.766884,1.377048,30.907215,0.711159

In [9]:
all_results_long.sort_values(['Senario', 'Forecast_Methods', 'Levels', 'Target_Service_Level']).reset_index(drop=True)

,Levels,Forecast_Methods,Target_Service_Level,Senario,Achieved_Service_Level,Holding_Costs,Backlogging_Costs,Fill_Rate
0,10,ETS,90%,BASE,0.852048,6.963762,4.778256,0.945830
1,10,ETS,95%,BASE,0.892986,8.649377,6.834147,0.960999
2,10,ETS,99%,BASE,0.941105,11.959015,18.434351,0.977956
3,11,ETS,90%,BASE,0.858076,3.484995,2.635797,0.900865
4,11,ETS,95%,BASE,0.896117,4.315378,3.979178,0.925712
...,...,...,...,...,...,...,...,...
283,11,LGBM_TD,95%,WLS_VAR_OR,0.930262,5.044730,2.878336,0.952174
284,11,LGBM_TD,99%,WLS_VAR_OR,0.958862,6.901549,8.868850,0.970360
285,12,LGBM_TD,90%,WLS_VAR_OR,0.848239,1.540670,1.798568,0.789213
286,12,LGBM_TD,95%,WLS_VAR_OR,0.874095,1.810115,3.109219,0.824208
287,12,LGBM_TD,99%,WLS_VAR_OR,0.910041,2.337294,11.502014,0.873003

In [10]:
# Optional save
# all_results_long.to_pickle(f"all_inventory_results_long_L{LEAD_TIME}.pkl")
# all_results_long.to_csv(f"all_inventory_results_long_L{LEAD_TIME}.csv", index=False)

# Mean table by scenario / level / target service level
all_results_long.sort_values(['Senario', 'Forecast_Methods', 'Levels', 'Target_Service_Level']).reset_index(drop=True)

,Levels,Forecast_Methods,Target_Service_Level,Senario,Achieved_Service_Level,Holding_Costs,Backlogging_Costs,Fill_Rate
0,10,ETS,90%,BASE,0.323701,1.269728,77.731422,0.779663
1,10,ETS,95%,BASE,0.397601,1.816297,139.204508,0.805777
2,10,ETS,99%,BASE,0.532692,3.235012,520.952246,0.852120
3,11,ETS,90%,BASE,0.518820,1.215590,23.617164,0.744415
4,11,ETS,95%,BASE,0.591677,1.661034,40.959302,0.784097
...,...,...,...,...,...,...,...,...
283,11,LGBM_TD,95%,WLS_VAR_OR,0.665257,2.153032,36.268467,0.831684
284,11,LGBM_TD,99%,WLS_VAR_OR,0.772045,3.417644,124.227861,0.887757
285,12,LGBM_TD,90%,WLS_VAR_OR,0.642472,0.876497,8.381645,0.657833
286,12,LGBM_TD,95%,WLS_VAR_OR,0.682859,1.062926,15.405647,0.698290
287,12,LGBM_TD,99%,WLS_VAR_OR,0.748747,1.452762,61.872711,0.762529

# BWE

In [10]:
collect_base_vs_ir_results

all_results_long = collect_base_vs_ir_results(
    lead_time=LEAD_TIME,
    filename_prefix=prefix,
)

In [11]:
all_results_long

,Levels,Forecast_Methods,Target_Service_Level,Senario,Achieved_Service_Level,Holding_Costs,Backlogging_Costs,Fill_Rate
0,10,LGBM,90%,BASE,0.857143,6.340248,4.448255,0.949918
1,10,LGBM,95%,BASE,0.897566,7.888741,6.491999,0.964040
2,10,LGBM,99%,BASE,0.942792,10.928069,18.820656,0.979051
3,11,LGBM,90%,BASE,0.869782,3.454602,2.512626,0.914778
4,11,LGBM,95%,BASE,0.905082,4.268535,3.804559,0.936449
...,...,...,...,...,...,...,...,...
283,11,ETS_MinT,95%,WLS_VAR_OR,0.908932,4.489914,3.507346,0.935949
284,11,ETS_MinT,99%,WLS_VAR_OR,0.947008,6.211284,10.504985,0.961092
285,12,ETS_MinT,90%,WLS_VAR_OR,0.816311,1.308883,2.099568,0.742274
286,12,ETS_MinT,95%,WLS_VAR_OR,0.844990,1.556003,3.663692,0.780554
287,12,ETS_MinT,99%,WLS_VAR_OR,0.885965,2.041593,13.719626,0.836553